#!/usr/bin/python

import sys

def extractOutput(file):
	outputs = []
	with open(file, 'r') as f:
		for line in f.readlines():
			line = line.strip()
			if line == 'or':
				continue
			output = line.split()
			outputs.append(output)
	return outputs


def main():
	if len(sys.argv) != 3:
		print "USAGE: testOutput.py expected_file output_file"
		exit(1)
	exp_file = sys.argv[1]
	out_file = sys.argv[2]
	actual_output = extractOutput(out_file)[0]
	expected_outputs = extractOutput(exp_file)
	for expected_output in expected_outputs:
		if actual_output == expected_output:
			print "PASSED: " + exp_file
			return
	print "FAILED: " + exp_file

if __name__ == "__main__":
	main()